# Generated by Django 5.2.8 on 2025-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_PROV', models.IntegerField()),
                ('SEQ_NO', models.IntegerField(unique=True)),
                ('FSIZE', models.FloatField()),
                ('URB', models.IntegerField()),
                ('RFACT', models.FloatField(blank=True, null=True)),
                ('TOINC', models.FloatField()),
                ('WAGES', models.IntegerField()),
                ('RPCINC', models.IntegerField()),
                ('CASH_ABROAD', models.IntegerField(blank=True, null=True)),
                ('CASH_DOMESTIC', models.IntegerField(blank=True, null=True)),
                ('TOTEX', models.FloatField()),
                ('PERCAPITA', models.FloatField(blank=True, null=True)),
                ('FOOD', models.FloatField()),
                ('CLOTH', models.IntegerField()),
                ('HEALTH', models.IntegerField()),
                ('TRANSPORT', models.IntegerField()),
                ('COMMUNICATION', models.IntegerField()),
                ('RECREATION', models.IntegerField()),
                ('EDUCATION', models.IntegerField()),
            ],
        ),
    ]
