# Generated by Django 5.2.8 on 2025-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calabarzonapp', '0002_province_remove_household_w_prov_household_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='URB',
            field=models.IntegerField(choices=[(1, 'Urban'), (2, 'Rural')]),
        ),
    ]
