# Generated by Django 5.2.8 on 2025-12-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calabarzonapp', '0003_province_description_alter_household_urb'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='province_images/'),
        ),
    ]
