# Generated by Django 5.2.8 on 2025-12-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calabarzonapp', '0004_province_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='image_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
