# Generated by Django 5.2.8 on 2025-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calabarzonapp', '0005_province_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='RPCINC',
        ),
        migrations.AlterField(
            model_name='household',
            name='PERCAPITA',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='RFACT',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='household',
            name='TOINC',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='TOTEX',
            field=models.FloatField(editable=False),
        ),
    ]
